# Generated by Django 4.2.7 on 2023-11-19 06:22

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField()),
                ('semester', models.CharField(max_length=11)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('num_of_sections', models.IntegerField()),
                ('modality', models.CharField(max_length=100)),
                ('credits', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_assignments', models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='TA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grader_status', models.BooleanField()),
                ('max_assignments', models.IntegerField(default=6, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.CharField(max_length=90)),
                ('password', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('home_address', models.CharField(max_length=90)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TAToCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
                ('ta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.ta')),
            ],
        ),
        migrations.AddField(
            model_name='ta',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.user'),
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_id', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('meeting_time', models.DateTimeField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.instructor', unique=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.section')),
                ('ta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.ta', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.section')),
                ('ta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.ta', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstructorToCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.instructor')),
            ],
        ),
        migrations.AddField(
            model_name='instructor',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.user'),
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.user')),
            ],
        ),
    ]
