# Generated by Django 4.2.7 on 2023-11-18 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAToSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.section')),
                ('ta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.ta')),
            ],
        ),
        migrations.CreateModel(
            name='InstructorToSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.instructor')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.section')),
            ],
        ),
    ]
