# Generated by Django 4.2.7 on 2023-12-04 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0002_remove_course_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='ta',
            name='skills',
            field=models.TextField(default='No skills listed', null=True),
        ),
    ]
