# Generated by Django 4.2.7 on 2023-11-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0002_tatosection_instructortosection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='sections',
        ),
        migrations.RemoveField(
            model_name='ta',
            name='sections',
        ),
    ]
